### PR TITLE
Adding .SCSS file syntax highlighting support

### PR DESCRIPTION
**Pull request by lukefiji**
I added .SCSS file syntax highlighting support for use with [WP-SCSS](https://wordpress.org/plugins/wp-scss/)

### CODE REVIEW

**Comment by shanept** [comment]
Looks great.
Can you squash it, so I may merge it? Thank you!

**Comment by lukefiji** [comment]
@shanept Well to be honest with you, I'm pretty beginner-level at Git, so this is actually my first-ever PR 🙌🏻. Would you mind pointing me in the right direction of how to do so?

**Comment by shanept** [comment]
Well welcome to git! You want to look at squashing commits with git rebase.

**Comment by lukefiji** [comment]
Alright, it's squashed! You should be good to go now

**Comment by shanept** [comment]
Looks great! Thanks for the PR!

**Pull request merged**
